export const peoples = [
  { name: "강다니엘", number: 1 },
  { name: "강동원", number: 1 },
  { name: "해린(뉴진스)", number: 1 },
  { name: "박지성", number: 1 },
  { name: "이말년(침착맨)", number: 1 },
  { name: "진 (BTS)", number: 1 },
  { name: "쯔양 (유튜버)", number: 1 },
  { name: "송강", number: 1 },
  { name: "해린(뉴진스)", number: 1 },
  { name: "임시완", number: 1 },
  { name: "트와이스 채영", number: 1 },
  { name: "지수 (BLACKPINK)", number: 1 },
  { name: "가을 (아이브)", number: 1 },
  { name: "레이 (아이브)", number: 2 },
  { name: "김태리", number: 2 },
  { name: "리사 (BLACKPINK)", number: 2 },
  { name: "이대호", number: 2 },
  { name: "지민 (BTS)", number: 2 },
  { name: "리즈 (아이브)", number: 2 },
  { name: "로제 (BLACKPINK)", number: 3 },
  { name: "뷔 (BTS)", number: 3 },
  { name: "소지섭", number: 3 },
  { name: "이종석", number: 3 },
  { name: "장혜진", number: 3 },
  { name: "트와이스 사나", number: 3 },
  { name: "하정우", number: 3 },
  { name: "신혜선", number: 3 },
  { name: "하니(뉴진스)", number: 4 },
  { name: "다니엘 (뉴진스)", number: 4 },
  { name: "박희순", number: 4 },
  { name: "조승우", number: 4 },
  { name: "하니(뉴진스)", number: 4 },
  { name: "궤도 (유튜버)", number: 4 },
  { name: "유재석", number: 5 },
  { name: "김래원", number: 5 },
  { name: "김태희", number: 5 },
  { name: "이서 (아이브)", number: 5 },
  { name: "안유진 (아이브)", number: 6 },
  { name: "김남주", number: 6 },
  { name: "비 (가수, 배우)", number: 6 },
  { name: "송중기", number: 6 },
  { name: "이강인", number: 6 },
  { name: "제니 (BLACKPINK)", number: 6 },
  { name: "조정석", number: 6 },
  { name: "하지원", number: 6 },
  { name: "이제훈", number: 6 },
  { name: "한소희", number: 7 },
  { name: "공유", number: 7 },
  { name: "곽튜브 (유튜버)", number: 7 },
  { name: "김세정", number: 7 },
  { name: "빠니보틀 (유튜버)", number: 7 },
  { name: "슈가 (BTS)", number: 7 },
  { name: "신동엽", number: 7 },
  { name: "제이홉 (BTS)", number: 7 },
  { name: "IU (아이유)", number: 7 },
  { name: "배수지", number: 7 },
  { name: "아이린", number: 7 },
  { name: "혜인 (뉴진스)", number: 8 },
  { name: "박보검", number: 8 },
  { name: "백지영", number: 8 },
  { name: "에일리", number: 8 },
  { name: "이민호", number: 8 },
  { name: "지진희", number: 8 },
  { name: "RM (BTS)", number: 8 },
  { name: "이진욱", number: 8 },
  { name: "정국 (BTS)", number: 9 },
  { name: "기안84", number: 9 },
  { name: "민지(뉴진스)", number: 9 },
  { name: "민지(뉴진스)", number: 9 },
  { name: "박경림", number: 9 },
  { name: "손흥민", number: 9 },
  { name: "트와이스 모모 ", number: 9 },
  { name: "한지민", number: 9 },
  { name: "황정민", number: 9 },
  { name: "장원영 (아이브)", number: 9 },
  { name: "방시혁", number: 9 },
];
